name: Lint Stage
on:
  pull_request:
    branches: [main]

jobs:
  build:
    name: Strict Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Git Repository
        uses: actions/checkout@v4

      - name: Settting Up Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Installing Node Dependencies
        run: npm ci

      - name: Checking Lint
        uses: reviewdog/action-eslint@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
